import '../../libraries.dart';

class AppColorManger {
  // static const Color primary = Color.fromARGB(255, 33, 40, 47);
  static const Color primary = Color.fromARGB(255, 33, 40, 47);
  static const Color primarySecond = Colors.orange;
  static const Color billkindHold = Colors.orangeAccent;
  static const Color billkindDecliend = Colors.grey;
  static const Color billkindPreparing = Colors.blueAccent;
  static const Color billkindReady = Colors.indigo;
  static const Color billkindNormal = Colors.green;
  static const Color billkindMoney = Colors.purple;
  static const Color billkindBackMoney = Colors.yellow;
  static const Color billkindBack = Colors.pink;
  static const Color backdark = Color.fromARGB(255, 56, 51, 51);
  static const Color backlight = Color.fromARGB(255, 228, 220, 220);
  static const Color order = Color.fromARGB(255, 68, 1, 251);
  static const Color orderDone = Color.fromARGB(255, 251, 68, 1);
  static Color sideBarIcon = Colors.blue[50]!;
  static Color sideBarSelected = Colors.grey[600]!;
  static Color sideBarSelectedHover = Colors.blue[600]!;
  static const Color grey = Colors.grey;
  static Color mainColor = const Color(0xff00BE84);
  static const Color darkScaffold = Color.fromARGB(255, 46, 45, 45);
  static const Color lightScaffold = Color.fromARGB(255, 249, 248, 249);
  static Color darkFontColor = const Color.fromARGB(255, 233, 230, 233);
  static const Color lightFontColor = Color(0xFF121212);
  static const Color pinkClr = Color(0xFFff4667);
  static const Color kColor1 = Color(0xff685959);
  static const Color kColor2 = Color(0xffADA79B);
  static const Color kColor3 = Color(0xffA5947F);
  static const Color kColor4 = Color(0xff738B71);
  static const Color kColor5 = Color(0xff6D454D);
  static const Color darkSettings = Color(0xff6132e4);
  static const Color accountSettings = Color(0xff73bc65);
  static const Color logOutSettings = Color(0xff5f95ef);
  static const Color notiSettings = Color(0xffdf5862);
  static const Color languageSettings = Color(0xffCB256C);
  static Color white = Get.theme.primaryColorDark;
  static const Color red = Colors.red;
  static Color greyLight = Get.theme.primaryColorDark;
  static Color black = Colors.black;
}
